import type { LanguageCode } from '../types';

type Dictionary = Record<string, string>;
export const supportedLanguages: LanguageCode[] = ['ru', 'en'];

const ruQuests: Dictionary = {
  questEarn100: 'Заработай 100 монет', questServe5: 'Обслужи 5 гостей', questMerge1: 'Сделай 1 объединение', questCoffee3: 'Улучши кофемашину до 3 уровня', questEarn500: 'Заработай 500 монет', questMerge3: 'Объедини 3 пары', questServe20: 'Обслужи 20 гостей', questUnlockDessert: 'Открой десертную витрину', questOven3: 'Улучши печь до 3 уровня', questWorker3: 'Получи капибару 3 уровня', questEarn1500: 'Заработай 1500 монет', questMerge8: 'Сделай 8 объединений', questServe50: 'Обслужи 50 гостей', questUnlockWindow: 'Открой столики у окна', questDessert4: 'Улучши витрину до 4 уровня', questEarn5000: 'Заработай 5000 монет', questWorker4: 'Получи капибару 4 уровня', questMerge15: 'Сделай 15 объединений', questServe100: 'Обслужи 100 гостей', questUnlockTerrace: 'Открой террасу', questLemonade4: 'Улучши бар лимонадов до 4 уровня', questEarn12000: 'Заработай 12000 монет', questMerge25: 'Сделай 25 объединений', questServe180: 'Обслужи 180 гостей', questCoffee8: 'Улучши кофемашину до 8 уровня', questUnlockDelivery: 'Открой доставку', questDelivery3: 'Улучши доставку до 3 уровня', questWorker5: 'Получи капибару 5 уровня', questEarn40000: 'Заработай 40000 монет', questServe300: 'Обслужи 300 гостей'
};
const enQuests: Dictionary = {
  questEarn100: 'Earn 100 coins', questServe5: 'Serve 5 guests', questMerge1: 'Merge once', questCoffee3: 'Upgrade coffee machine to level 3', questEarn500: 'Earn 500 coins', questMerge3: 'Merge 3 pairs', questServe20: 'Serve 20 guests', questUnlockDessert: 'Unlock dessert case', questOven3: 'Upgrade oven to level 3', questWorker3: 'Get a level 3 capybara', questEarn1500: 'Earn 1500 coins', questMerge8: 'Make 8 merges', questServe50: 'Serve 50 guests', questUnlockWindow: 'Unlock window tables', questDessert4: 'Upgrade dessert case to level 4', questEarn5000: 'Earn 5000 coins', questWorker4: 'Get a level 4 capybara', questMerge15: 'Make 15 merges', questServe100: 'Serve 100 guests', questUnlockTerrace: 'Unlock terrace', questLemonade4: 'Upgrade lemonade bar to level 4', questEarn12000: 'Earn 12000 coins', questMerge25: 'Make 25 merges', questServe180: 'Serve 180 guests', questCoffee8: 'Upgrade coffee machine to level 8', questUnlockDelivery: 'Unlock delivery', questDelivery3: 'Upgrade delivery to level 3', questWorker5: 'Get a level 5 capybara', questEarn40000: 'Earn 40000 coins', questServe300: 'Serve 300 guests'
};

export const localization: Record<LanguageCode, Dictionary> = {
  ru: {
    title: 'Капи Кафе', subtitle: 'Merge Тайкун', play: 'Играть', continue: 'Продолжить', coins: 'Монеты', stars: 'Звёзды', cafeLevel: 'Кафе', settings: 'Настройки', shop: 'Магазин', workers: 'Капибары', dishes: 'Блюда', upgrades: 'Улучшения', quests: 'Задания', reward: 'Бонус', close: 'Закрыть', buyWorker: 'Купить капибару', buyDish: 'Купить блюдо', upgrade: 'Улучшить', unlock: 'Открыть', watchAdCoins: 'Смотреть рекламу: получить 300 монет', watchAdOffline: 'Смотреть рекламу: x2 офлайн-доход', watchAdBoost: 'Смотреть рекламу: ускорить кафе на 2 минуты', watchAdWorker: 'Смотреть рекламу: бесплатная капибара', notEnoughCoins: 'Не хватает монет', notEnoughStars: 'Нужны звёзды', noSlots: 'Нет свободных слотов', music: 'Музыка', sfx: 'Звуки', language: 'Язык', login: 'Войти через Яндекс ID', offlineTitle: 'Кафе работало без тебя!', offlineClaim: 'Забрать', questDone: 'Задание выполнено!', rewardGranted: 'Награда получена!', adUnavailable: 'Реклама сейчас недоступна', mockSdk: 'Локальный mock SDK', tutorial1: 'Тапай по кофемашине и получай первые монеты.', tutorial2: 'Купи новую капибару для кафе.', tutorial3: 'Перетащи одинаковые капибары друг на друга.', tutorial4: 'Улучши кофемашину, чтобы зарабатывать быстрее.', tutorial5: 'Выполняй задания и получай звёзды.', tutorial6: 'Магазин и бонусы всегда внизу экрана.', tutorialNext: 'Понятно', worker1: 'Капибара-новичок', worker2: 'Капибара-бариста', worker3: 'Капибара-пекарь', worker4: 'Капибара-мастер', worker5: 'Капибара-шеф', dish1: 'Кофе', dish2: 'Латте', dish3: 'Круассан', dish4: 'Маффин', dish5: 'Торт', dish6: 'Лимонад', dish7: 'Сэндвич', dish8: 'Мороженое', stationCoffee: 'Кофемашина', stationOven: 'Печь', stationDessert: 'Витрина', stationLemonade: 'Бар лимонадов', stationDelivery: 'Доставка', zoneCoffee: 'Стойка кофе', zoneDessert: 'Десертная витрина', zoneWindow: 'Столики у окна', zoneTerrace: 'Летняя терраса', zoneDelivery: 'Доставка заказов', dailyQuest: 'Ежедневная цель', ...ruQuests
  },
  en: {
    title: 'Capi Cafe', subtitle: 'Merge Tycoon', play: 'Play', continue: 'Continue', coins: 'Coins', stars: 'Stars', cafeLevel: 'Cafe', settings: 'Settings', shop: 'Shop', workers: 'Capybaras', dishes: 'Dishes', upgrades: 'Upgrades', quests: 'Quests', reward: 'Bonus', close: 'Close', buyWorker: 'Buy capybara', buyDish: 'Buy dish', upgrade: 'Upgrade', unlock: 'Unlock', watchAdCoins: 'Watch ad: get 300 coins', watchAdOffline: 'Watch ad: x2 offline income', watchAdBoost: 'Watch ad: speed up cafe for 2 minutes', watchAdWorker: 'Watch ad: free capybara', notEnoughCoins: 'Not enough coins', notEnoughStars: 'Need stars', noSlots: 'No free slots', music: 'Music', sfx: 'Sounds', language: 'Language', login: 'Login with Yandex ID', offlineTitle: 'Cafe worked while you were away!', offlineClaim: 'Claim', questDone: 'Quest complete!', rewardGranted: 'Reward granted!', adUnavailable: 'Ad unavailable now', mockSdk: 'Local mock SDK', tutorial1: 'Tap the coffee machine to earn coins.', tutorial2: 'Buy a new capybara.', tutorial3: 'Drag matching capybaras onto each other.', tutorial4: 'Upgrade the coffee machine.', tutorial5: 'Complete quests and collect stars.', tutorial6: 'Shop and bonuses are at the bottom.', tutorialNext: 'Got it', worker1: 'Rookie capybara', worker2: 'Barista capybara', worker3: 'Baker capybara', worker4: 'Master capybara', worker5: 'Chef capybara', dish1: 'Coffee', dish2: 'Latte', dish3: 'Croissant', dish4: 'Muffin', dish5: 'Cake', dish6: 'Lemonade', dish7: 'Sandwich', dish8: 'Ice cream', stationCoffee: 'Coffee machine', stationOven: 'Oven', stationDessert: 'Dessert case', stationLemonade: 'Lemonade bar', stationDelivery: 'Delivery', zoneCoffee: 'Coffee counter', zoneDessert: 'Dessert case', zoneWindow: 'Window tables', zoneTerrace: 'Summer terrace', zoneDelivery: 'Delivery desk', dailyQuest: 'Daily goal', ...enQuests
  }
};
